In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import re

In [3]:
df1= pd.read_csv('C:/files/programming/Python/projects/rakshagrid/data/scam-dialogue/scam-dialogue_all.csv')

In [4]:
df1.head()

                                            dialogue type  label
0  caller: Hello, is this John Smith? receiver: Y...  ssn      1
1  caller: Hello, my name is Officer Johnson from...  ssn      1
2  caller: Hello, is this Mr. Johnson? receiver: ...  ssn      1
3  caller: Hello, my name is Officer Johnson from...  ssn      1
4  caller: Hello, this is Officer Johnson from th...  ssn      1

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   dialogue  1600 non-null   object
 1   type      1600 non-null   object
 2   label     1600 non-null   int64
dtypes: int64(1), object(2)
memory usage: 37.6+ KB

In [6]:
df1.shape

(1600, 3)

In [7]:
df_final = pd.DataFrame(df1)

In [8]:
df1 = df1.rename(columns={"dialogue":"text","type":"category"})

In [9]:
df1.head()

                                                text category  label
0  caller: Hello, is this John Smith? receiver: Y...      ssn      1
1  caller: Hello, my name is Officer Johnson from...      ssn      1
2  caller: Hello, is this Mr. Johnson? receiver: ...      ssn      1
3  caller: Hello, my name is Officer Johnson from...      ssn      1
4  caller: Hello, this is Officer Johnson from th...      ssn      1

In [10]:
df1['source']="scam_dialogue_synth"
df1['source_url']=np.nan

In [11]:
df1 = df1[["text","label","category","source","source_url"]]

In [12]:
df1

,text,label,category,source,source_url
0,"caller: Hello, is this John Smith? receiver: Y...",1,ssn,scam_dialogue_synth,NaN
1,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN
2,"caller: Hello, is this Mr. Johnson? receiver: ...",1,ssn,scam_dialogue_synth,NaN
3,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN
4,"caller: Hello, this is Officer Johnson from th...",1,ssn,scam_dialogue_synth,NaN
...,...,...,...,...,...
1595,"caller: Hello, is this 555-1234? receiver: Yes...",0,wrong,scam_dialogue_synth,NaN
1596,"caller: Hi, is this 555-1234? receiver: No, th...",0,wrong,scam_dialogue_synth,NaN
1597,"caller: Hi, is this John? receiver: No, this i...",0,wrong,scam_dialogue_synth,NaN
1598,"caller: Hi, is this 555-1234? receiver: No, th...",0,wrong,scam_dialogue_synth,NaN
1599,"caller: Hi, is this 555-1234? receiver: No, th...",0,wrong,scam_dialogue_synth,NaN

In [13]:
def load_txt(path, label, src, category="unknown"):
    with open(path, encoding="utf-8") as f:
        lines = [l.strip() for l in f.readlines() if l.strip()]
    # strip leading "1.  " / "23. " numbering if present
    lines = [re.sub(r"^\d+\.\s*", "", l) for l in lines]
    return pd.DataFrame({
        "text": lines,
        "label": label,
        "category": category,
        "source": src,
        "source_url": np.nan
    })

In [14]:
df2_scam = load_txt("C:/files/programming/Python/projects/rakshagrid/data/scamandnonscamconvo/English_Scam.txt",label=1 , src='scam_synth')
df2_nonscam = load_txt("C:/files/programming/Python/projects/rakshagrid/data/scamandnonscamconvo/English_NonScam.txt",label=0 , src='nonscam_synth')

In [15]:
df2_scam

,text,label,category,source,source_url
0,[Greetings] I am calling from the government g...,1,unknown,scam_synth,NaN
1,"[Greetings], we are calling on behalf of a cha...",1,unknown,scam_synth,NaN
2,Congratulations! You have won a free vacation ...,1,unknown,scam_synth,NaN
3,[Greetings]. I am calling from the technical s...,1,unknown,scam_synth,NaN
4,"[Greetings], this is [Title][Name] from the l...",1,unknown,scam_synth,NaN
...,...,...,...,...,...
395,"[Greetings], we are reaching out to finalize y...",1,unknown,scam_synth,NaN
396,"[Greetings], thank you for being an active mem...",1,unknown,scam_synth,NaN
397,"[Greetings], you have been approved for a scho...",1,unknown,scam_synth,NaN
398,"[Greetings], you have been offered an invitati...",1,unknown,scam_synth,NaN
399,"[Greetings], we are conducting a financial swe...",1,unknown,scam_synth,NaN

In [16]:
df2 = pd.concat([df2_scam,df2_nonscam],ignore_index=True)

In [17]:
df2.head()

,text,label,category,source,source_url
0,[Greetings] I am calling from the government g...,1,unknown,scam_synth,NaN
1,"[Greetings], we are calling on behalf of a cha...",1,unknown,scam_synth,NaN
2,Congratulations! You have won a free vacation ...,1,unknown,scam_synth,NaN
3,[Greetings]. I am calling from the technical s...,1,unknown,scam_synth,NaN
4,"[Greetings], this is [Title][Name] from the l...",1,unknown,scam_synth,NaN

In [18]:
df3 = pd.read_csv('C:/files/programming/Python/projects/rakshagrid/data/youtube_scam_call_transcripts/FullTranscriptData.csv')

In [19]:
df3.head()

,ID,Source,Content,Char_Len
0,0,https://www.youtube.com/watch?v=UG-KjCSt14k&ab...,hi yeah I've got an email here about a laptop ...,224
1,1,https://www.patreon.com/JimBrowning/posts?filt...,Hello This is British Telecom technical depart...,398
2,2,https://www.youtube.com/watch?v=P6dhteJIY48&ab...,hello this call is from Interpol the purpose o...,186
3,3,https://www.youtube.com/watch?v=HlTpousFPsM&ab...,hi this is from Amazon customer service we hav...,361
4,4,https://www.youtube.com/watch?v=8sT121uUFOo&ab...,this is calling with the vehicle service depar...,411

In [20]:
df3.rename(columns={"Source":'source_url',"Content":"text"},inplace=True)

In [21]:
df3.head()

,ID,source_url,text,Char_Len
0,0,https://www.youtube.com/watch?v=UG-KjCSt14k&ab...,hi yeah I've got an email here about a laptop ...,224
1,1,https://www.patreon.com/JimBrowning/posts?filt...,Hello This is British Telecom technical depart...,398
2,2,https://www.youtube.com/watch?v=P6dhteJIY48&ab...,hello this call is from Interpol the purpose o...,186
3,3,https://www.youtube.com/watch?v=HlTpousFPsM&ab...,hi this is from Amazon customer service we hav...,361
4,4,https://www.youtube.com/watch?v=8sT121uUFOo&ab...,this is calling with the vehicle service depar...,411

In [22]:
df3["label"]=1

In [23]:
df3["category"]="unkown"

In [24]:
df3["source"]="youtube_real"

In [25]:
df3=df3[["text","label","category","source","source_url"]]

In [26]:
df3.head()

,text,label,category,source,source_url
0,hi yeah I've got an email here about a laptop ...,1,unkown,youtube_real,https://www.youtube.com/watch?v=UG-KjCSt14k&ab...
1,Hello This is British Telecom technical depart...,1,unkown,youtube_real,https://www.patreon.com/JimBrowning/posts?filt...
2,hello this call is from Interpol the purpose o...,1,unkown,youtube_real,https://www.youtube.com/watch?v=P6dhteJIY48&ab...
3,hi this is from Amazon customer service we hav...,1,unkown,youtube_real,https://www.youtube.com/watch?v=HlTpousFPsM&ab...
4,this is calling with the vehicle service depar...,1,unkown,youtube_real,https://www.youtube.com/watch?v=8sT121uUFOo&ab...

In [27]:
df = pd.concat([df1,df2,df3],ignore_index=True)
print(df.shape,df['label'].value_counts(),df['source'].value_counts())

(2643, 5) label
1    1443
0    1200
Name: count, dtype: int64 source
scam_dialogue_synth    1600
scam_synth              400
nonscam_synth           400
youtube_real            243
Name: count, dtype: int64

In [28]:
# wont clean as transformer is being used so will destroy signal

In [29]:
df.isnull().sum()

text             0
label            0
category         0
source           0
source_url    2400
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(5)

In [31]:
df = df.drop_duplicates(subset="text").reset_index(drop=True)

In [32]:
df.shape

(2638, 5)

In [33]:
# Filling placeholders

PLACEHOLDER_MAP = {
    r"\[Company\]": "Acme Corp",
    r"\[Name\]": "John",
    r"\[Title\]": "Mr.",
    r"\[Date\]": "Monday",
    r"\[Time\]": "3 PM",
    r"\[Product\]": "your order",
    r"\[Number\]": "1234",
    r"\[City\]": "Boston",
}
def fill_placeholders(t):
    for pattern, repl in PLACEHOLDER_MAP.items():
        t = re.sub(pattern, repl, t)
    return t

df["text"] = df["text"].apply(fill_placeholders)

In [34]:
# normalizing speaker structure
def count_turns(t):
    return len(re.findall(r"\b(caller|receiver):", t, flags=re.IGNORECASE))

df["turn_count"] = df["text"].apply(count_turns)

In [35]:
# Feature engineering

In [36]:
URGENCY_WORDS = r"\b(immediately|urgent|now|verify|suspend|arrest|warrant|legal action|fine|penalty|act now|limited time|final notice)\b"
MONEY_WORDS = r"\b(gift card|wire transfer|bitcoin|crypto|bank account|social security|ssn|routing number|card number|cvv|otp|one[- ]time password)\b"
AUTHORITY_WORDS = r"\b(irs|police|fbi|government|officer|department|agent|court|federal)\b"

df["char_len"] = df["text"].str.len()
df["word_count"] = df["text"].str.split().apply(len)
df["turn_count"] = df["text"].apply(count_turns)
df["placeholder_count"] = df["text"].str.count(r"\[[A-Za-z]+\]")   
df["urgency_word_count"] = df["text"].str.lower().str.count(URGENCY_WORDS)
df["money_word_count"] = df["text"].str.lower().str.count(MONEY_WORDS)
df["authority_word_count"] = df["text"].str.lower().str.count(AUTHORITY_WORDS)
df["has_phone_number"] = df["text"].str.contains(r"\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b").astype(int)
df["exclaim_count"] = df["text"].str.count("!")

In [37]:
df.head()

,text,label,category,source,source_url,turn_count,char_len,word_count,placeholder_count,urgency_word_count,money_word_count,authority_word_count,has_phone_number,exclaim_count
0,"caller: Hello, is this John Smith? receiver: Y...",1,ssn,scam_dialogue_synth,NaN,20,1723,301,0,4,6,2,0,0
1,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN,17,1912,338,0,4,8,3,0,1
2,"caller: Hello, is this Mr. Johnson? receiver: ...",1,ssn,scam_dialogue_synth,NaN,13,1151,193,0,4,5,2,0,0
3,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN,20,2166,377,0,5,9,2,0,0
4,"caller: Hello, this is Officer Johnson from th...",1,ssn,scam_dialogue_synth,NaN,18,1676,294,0,7,5,1,0,0

In [38]:
print(df.groupby(["source","label"]).size())

source               label
nonscam_synth        0        400
scam_dialogue_synth  0        799
                     1        799
scam_synth           1        397
youtube_real         1        243
dtype: int64

In [39]:
(df ==0).sum()

text                       0
label                   1199
category                   0
source                     0
source_url                 0
turn_count              1040
char_len                   0
word_count                 0
placeholder_count       1898
urgency_word_count      1302
money_word_count        1922
authority_word_count    1962
has_phone_number        2511
exclaim_count           1406
dtype: int64

In [40]:
df.shape

(2638, 14)

In [41]:
df.head()

,text,label,category,source,source_url,turn_count,char_len,word_count,placeholder_count,urgency_word_count,money_word_count,authority_word_count,has_phone_number,exclaim_count
0,"caller: Hello, is this John Smith? receiver: Y...",1,ssn,scam_dialogue_synth,NaN,20,1723,301,0,4,6,2,0,0
1,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN,17,1912,338,0,4,8,3,0,1
2,"caller: Hello, is this Mr. Johnson? receiver: ...",1,ssn,scam_dialogue_synth,NaN,13,1151,193,0,4,5,2,0,0
3,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN,20,2166,377,0,5,9,2,0,0
4,"caller: Hello, this is Officer Johnson from th...",1,ssn,scam_dialogue_synth,NaN,18,1676,294,0,7,5,1,0,0

In [42]:
from sklearn.model_selection import train_test_split

strat_key = df["label"].astype(str) + "_" + df["source"]

train_df, temp_df = train_test_split(
    df, test_size=0.2, stratify=strat_key, random_state=42
)

temp_strat_key = temp_df["label"].astype(str) + "_" + temp_df["source"]
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, stratify=temp_strat_key, random_state=42
)

In [43]:
train_df.shape

(2110, 14)

In [44]:
temp_df.shape

(528, 14)

In [45]:
train_df.head()

,text,label,category,source,source_url,turn_count,char_len,word_count,placeholder_count,urgency_word_count,money_word_count,authority_word_count,has_phone_number,exclaim_count
1004,"caller: Hello, is this Mr. Johnson? receiver: ...",0,insurance,scam_dialogue_synth,NaN,15,1554,266,0,0,0,0,0,5
1646,"[Greetings], this is John from Acme Corp. You ...",1,unknown,scam_synth,NaN,0,216,39,2,0,1,0,0,0
977,"caller: Hi, I'm calling from XYZ Delivery. I j...",0,delivery,scam_dialogue_synth,NaN,10,685,117,0,0,0,0,0,3
2067,"[Greetings], this is Acme Corp Observatory. We...",0,unknown,nonscam_synth,NaN,0,174,28,1,0,0,0,0,0
1743,"[Greetings]! I am John, a recruiter from Tech ...",1,unknown,scam_synth,NaN,0,385,70,2,0,1,0,0,1

In [46]:
temp_df.head()

,text,label,category,source,source_url,turn_count,char_len,word_count,placeholder_count,urgency_word_count,money_word_count,authority_word_count,has_phone_number,exclaim_count
1588,"caller: Hello, is this 555-1234? receiver: Yes...",0,wrong,scam_dialogue_synth,NaN,10,628,112,0,0,0,0,0,1
1075,"caller: Hello, my name is John and I'm calling...",0,insurance,scam_dialogue_synth,NaN,12,1781,296,0,1,0,1,0,0
3,"caller: Hello, my name is Officer Johnson from...",1,ssn,scam_dialogue_synth,NaN,20,2166,377,0,5,9,2,0,0
720,"caller: Hello, is this Mrs. Johnson? receiver...",1,reward,scam_dialogue_synth,NaN,13,936,161,0,1,4,1,0,1
990,"caller: Hi, I'm calling to confirm the deliver...",0,delivery,scam_dialogue_synth,NaN,8,767,135,0,1,0,0,0,0

In [47]:
strat_key.value_counts()

1_scam_dialogue_synth    799
0_scam_dialogue_synth    799
0_nonscam_synth          400
1_scam_synth             397
1_youtube_real           243
Name: count, dtype: int64

In [49]:
val_df.shape

(264, 14)

In [50]:
test_df.shape

(264, 14)

In [54]:
BASE = "C:/files/programming/Python/projects/rakshagrid/data/"
train_df.to_csv(f"{BASE}/train.csv", index=False)
val_df.to_csv(f"{BASE}/val.csv", index=False)
test_df.to_csv(f"{BASE}/test.csv", index=False)
df.to_csv(f"{BASE}/combined_all.csv", index=False)